#pragma line 1 "sha256/src/sha256.c" ::: -10
#pragma line 1 "sha256/src/sha256.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 421 "/opt/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "sha256/src/sha256.c" 2 ::: 184
#pragma line 1 "sha256/src/sha256.h" 1 ::: 185
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdbool.h" 1 3 ::: 188
#pragma line 4 "sha256/src/sha256.h" 2 ::: 218
#pragma line 2 "sha256/src/sha256.c" 2 ::: 228
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 230
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 258
#pragma line 122 "/usr/include/features.h" 3 4 ::: 355
#pragma line 156 "/usr/include/features.h" 3 4 ::: 380
#pragma line 180 "/usr/include/features.h" 3 4 ::: 382
#pragma line 191 "/usr/include/features.h" 3 4 ::: 385
#pragma line 343 "/usr/include/features.h" 3 4 ::: 416
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 420
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 455
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 462
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 485
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 526
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 532
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 550
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 556
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 560
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 562
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 566
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 576
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 629
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 670
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 695
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 719
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 720
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 722
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 724
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 725
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 750
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 761
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 766
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 767
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 768
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 774
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 815
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 818
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 820
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 848
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 850
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 852
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 913
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 920
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 938
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 943
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 954
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 1023
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1037
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1040
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1041
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1073
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1089
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1114
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1117
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1122
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1144
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1165
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1168
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1179
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1189
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1191
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1195
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1244
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1245
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1251
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1253
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1273
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1284
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1325
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1355
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1381
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1385
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1400
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1412
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1418
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1420
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1430
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1452
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1468
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1485
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1517
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1563
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1577
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1580
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1656
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1695
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1736
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1849
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1912
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1961
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1972
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2002
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2030
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2062
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2074
#pragma line 4 "sha256/src/sha256.c" 2 ::: 2077
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2078
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2111
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2136
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2139
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2149
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2178
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2196
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2197
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2253
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2254
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2291
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2293
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2297
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2300
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2318
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2319
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2321
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2323
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2331
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2349
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2352
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2355
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2357
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2358
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2392
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2398
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2414
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2416
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2538
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2552
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2573
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2590
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2612
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2620
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2629
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2630
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2651
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2654
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2657
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2660
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2663
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2664
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2665
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2690
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2693
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2703
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 2738
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 2769
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2792
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2794
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 2796
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2797
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 2801
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2841
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2852
#pragma line 118 "/usr/include/time.h" 3 4 ::: 2873
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2881
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 2883
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2918
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 2963
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2993
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 2997
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3015
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3026
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3028
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3050
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3054
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3076
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3078
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3080
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3081
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3104
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3126
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3203
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3234
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3235
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3378
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3407
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3432
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3457
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3460
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3469
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 3482
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 3489
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 3501
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 3512
#pragma line 634 "/usr/include/stdlib.h" 3 4 ::: 3558
#pragma line 657 "/usr/include/stdlib.h" 3 4 ::: 3567
#pragma line 712 "/usr/include/stdlib.h" 3 4 ::: 3574
#pragma line 728 "/usr/include/stdlib.h" 3 4 ::: 3580
#pragma line 752 "/usr/include/stdlib.h" 3 4 ::: 3595
#pragma line 911 "/usr/include/stdlib.h" 3 4 ::: 3746
#pragma line 947 "/usr/include/stdlib.h" 3 4 ::: 3748
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 3757
#pragma line 955 "/usr/include/stdlib.h" 2 3 4 ::: 3775
#pragma line 5 "sha256/src/sha256.c" 2 ::: 3778
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 3779
#pragma line 29 "/usr/include/string.h" 3 4 ::: 3800
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3805
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3830
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 3833
#pragma line 92 "/usr/include/string.h" 3 4 ::: 3870
#pragma line 124 "/usr/include/string.h" 3 4 ::: 3873
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 3910
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 3953
#pragma line 207 "/usr/include/string.h" 3 4 ::: 3975
#pragma line 231 "/usr/include/string.h" 3 4 ::: 3977
#pragma line 258 "/usr/include/string.h" 3 4 ::: 3982
#pragma line 278 "/usr/include/string.h" 3 4 ::: 3985
#pragma line 310 "/usr/include/string.h" 3 4 ::: 3995
#pragma line 337 "/usr/include/string.h" 3 4 ::: 4000
#pragma line 393 "/usr/include/string.h" 3 4 ::: 4021
#pragma line 439 "/usr/include/string.h" 3 4 ::: 4052
#pragma line 484 "/usr/include/string.h" 3 4 ::: 4075
#pragma line 512 "/usr/include/string.h" 3 4 ::: 4081
#pragma line 550 "/usr/include/string.h" 3 4 ::: 4105
#pragma line 6 "sha256/src/sha256.c" 2 ::: 4131
#pragma line 1 "sha256/src/sha256_impl.h" 1 ::: 4132
#pragma line 7 "sha256/src/sha256.c" 2 ::: 4148
