// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_sha256 (
unsigned char data[256],
unsigned int base_offset,
unsigned int bytes,
unsigned char digest[32]);
